runmode: debug                 # 开发模式, debug, release, test
addr: 8000                  # HTTP绑定端口
name: dbger              # API Server的名字
ping_url: http://127.0.0.1:8000   # pingServer函数请求的API服务器的ip:port
ping_max_num: 10           # pingServer函数try的次数
jwt_secret: dbgerdemojwtseCrect666!@#123
gormlog: true

# tls
tls:
  https_open: false
  addr: 8080
  cert: configs/server.crt
  key: configs/server.key

# logger
log:
  logger_file: logs/server.log
  logger_max_size: 1024 # megabytes
  logger_max_backups: 7
  logger_max_age: 31 # days

# database
db:
  name: dbger
  addr: 127.0.0.1:3306 # host:port
  username: root
  password: 123456
